config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  #,:users,:events,:permissions,:accounts

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/timekeeper.rb
class Timekeeper < ApplicationRecord
	#Timeline object in Activerecord
	has_many :events, inverse_of :timekeeper 
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :timekeepers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
        redirect_to @event
      else
        render  'edit'
      end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :time_stamp, :description, :owner)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |e| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
      <%= e.label :event %><br>
      <%= e.text_field :title %>
  </p>
  <p>
      <%= e.label :summary %><br>
      <%= e.text_area :description %>
  </p>
  <p>
      <%= e.submit %>
  </p>
  <%= e.hidden_field :owner, :value => "Brian"  %>
  <%= e.hidden_field :time_stamp, :value => DateTime.now  %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Event Listing</h1>

<%= link_to 'New event', new_event_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Time</th>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.time_stamp %></td>
      <td><%= link_to 'Show', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <Strong>Event</Strong>:<br>
  <%= @event.title %><br>@ <%= @event.time_stamp %>
</p>
<p>
  <Strong>Description</Strong>
  <%= @event.description %>
</p>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timeline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/timelines/new.html.erb
<h1>New Event</h1>

<%= form_for :event, url: events_path do |e| %>
  <p>
      <%= e.label :event %><br>
      <%= e.text_field :event %>
  </p>
  <p>
      <%= e.label :summary %><br>
      <%= e.text_area :summary %>
  </p>
  <p>
      <%= e.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timeline</title>
    <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
			<!--<link rel="stylesheet" href="assets/css/main.css" />-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
  </head>
  <body>
    <h1>Welcome#index</h1>
    <p>Find me in app/views/welcome/index.html.erb</p>
    <%= link_to 'My Timeline', controller: 'events' %>
  </body>
</html>